services:
  app:
    container_name: yoprint
    image: yoprint:0.1
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - redis
    networks:
      - backend
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
